### ISSUE TITLE
collect2: error: ld returned 1 exit status

### ISSUE THREAD

**Issue by nosqlcoco** [Linzecong/MFCC-DTW#1]
clone到本地，启动“g++ main.cpp -o output -lstdc++”报错如下：
/tmp/ccjS9i7I.o：在函数‘main’中：
main.cpp:(.text+0x45)：对‘WaveFunction::WaveFunction(int, int)’未定义的引用
main.cpp:(.text+0x8a)：对‘WaveFunction::getMFCCs(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >)’未定义的引用
main.cpp:(.text+0xe0)：对‘WaveFunction::getMFCCs(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >)’未定义的引用
main.cpp:(.text+0x131)：对‘WaveFunction::addOrderDifference(std::vector<std::vector<float, std::allocator<float> >, std::allocator<std::vector<float, std::allocator<float> > > >)’未定义的引用
main.cpp:(.text+0x1a1)：对‘WaveFunction::addOrderDifference(std::vector<std::vector<float, std::allocator<float> >, std::allocator<std::vector<float, std::allocator<float> > > >)’未定义的引用
main.cpp:(.text+0x21e)：对‘WaveFunction::ComputeDTW(std::vector<std::vector<float, std::allocator<float> >, std::allocator<std::vector<float, std::allocator<float> > > >, std::vector<std::vector<float, std::allocator<float> >, std::allocator<std::vector<float, std::allocator<float> > > >)’未定义的引用
collect2: error: ld returned 1 exit status

**Comment by Linzecong** [comment]
要链接WaveFunction.cpp
