### ISSUE TITLE
There are 2 minute errors in the WaveFunction.c and main.c

### ISSUE THREAD

**Issue by vyi** [Linzecong/MFCC-DTW#3]
**1**

In the body of the `addOrderDifference` function you have defined 

```
vector<vector<float>> addOrderDifference(vector<vector<float> > mfccs){
      // ...
        }
```
This causes an error when compiling the project:
Following code solves it ( By adding WaveFunction:: to name of function)

```
vector<vector<float>> WaveFunction::addOrderDifference(vector<vector<float> > mfccs){
      // Code 
        }
```

**2**

in main.c change the first line
`#include"wavefunction.h"`

to 

`#include"WaveFunction.h"`

Thats all.

**Comment by Linzecong** [comment]
thanks
